name: 'medical_warehouse'
version: '1.0'
config-version: 2

profile: 'medical_warehouse_profile'  # this should match the profile name in profiles.yml

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
