version: 2

models:
  - name: stg_telegram_messages
    description: "Staging table for raw Telegram messages, cleaned and typed."
    columns:
      - name: message_id
        description: "Unique identifier for each message"
      - name: channel_name
        description: "Name of the Telegram channel"
      - name: message_date
        description: "Date and time the message was posted"
      - name: text_content
        description: "Content of the message"
      - name: view_count
        description: "Number of views the message received"
      - name: forward_count
        description: "Number of times the message was forwarded"
      - name: has_image
        description: "Flag indicating if the message contains an image"
      - name: message_length
        description: "Length of the message text in characters"
