version: 2

models:
  - name: stg_yolo_detections
    description: "Staging model for YOLO image detection results"
    columns:
      - name: image_file
        description: "Image filename"
      - name: detected_class
        description: "Detected object class from YOLO"
      - name: confidence_score
        description: "Confidence score of the detection"
      - name: image_category
        description: "Derived image category (promotional, product_display, lifestyle, other)"
